name: Process ATLAS ROOT Open Data v2

on:
  workflow_dispatch:
    inputs:
      data_file:
        description: 'Path to the Data URLs input file'
        default: 'data.csv'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.read_file.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read CSV File and Prepare Jobs
        id: read_file
        run: |
          files=$(jq -R -s -c 'split("\n")[:-1]' < ${{ github.event.inputs.data_file }})
          echo "files=$files" >> $GITHUB_OUTPUT

  process-file:
    needs: setup
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to allow pushing changes
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(needs.setup.outputs.files) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run ROOT Script in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: rootproject/root:latest
          options: --rm -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            python3 gamma-gamma-analysis-v1.py "${{ matrix.file }}"

      - name: Commit and Push Histogram Plot
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Only add files if they exist
          if ls plots/histogram_*.png plots/histogram_*.root 1> /dev/null 2>&1; then
            git add plots/histogram_*.png plots/histogram_*.root
            git diff --cached --exit-code || git commit -m "Add updated histogram plot" --allow-empty
          else
            echo "No plot generated"
          fi

          # Pull the latest changes and rebase before pushing
          git fetch origin main
          git stash push -m "Stash uncommitted changes for rebase"
          git rebase origin/main
          git stash pop || true  # Apply stashed changes if any
          git push --force-with-lease origin HEAD:main

  merge-root-files:
    needs: process-file
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to allow pushing changes

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Verify .root Files
        run: |
          echo "Listing all .root files in plots directory:"
          ls -lh plots/*.root || echo "No .root files found in plots directory"

      - name: Set up ROOT environment with Docker and Merge Files
        uses: addnab/docker-run-action@v3
        with:
          image: rootproject/root:latest
          options: --rm -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace/plots
            # Use hadd to merge all ROOT files in the plots directory
            hadd /workspace/plots/merged_histograms.root /workspace/plots/histogram_*.root

      - name: Commit and Push Merged ROOT File
        if: always()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Add and commit the merged ROOT file
          git add plots/merged_histograms.root || echo "No merged ROOT file generated"
          git diff --cached --exit-code || git commit -m "Add merged ROOT file" --allow-empty
          
          # Fetch the latest changes, rebase, and push
          git fetch origin main
          git rebase origin/main
          git push --force-with-lease origin HEAD:main || (echo "Rebase failed, retrying..." && git pull --rebase origin main && git push --force-with-lease origin HEAD:main)
          
  generate-png:
    needs: merge-root-files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run root-to-png.py in Docker
        uses: addnab/docker-run-action@v3
        with:
          image: rootproject/root:latest
          options: --rm -v ${{ github.workspace }}:/workspace
          run: |
            cd /workspace
            python3 root-to-png.py "plots/merged_histograms.root"

      - name: Commit and Push Merged PNG File
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add plots/merged_histograms.png || echo "No merged PNG file generated"
          git diff --cached --exit-code || git commit -m "Add merged histogram as PNG" --allow-empty
          git push --force-with-lease origin HEAD:main