- name: Commit and Push Histogram Plot
if: always()
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
run: |
  git config --local user.email "action@github.com"
  git config --local user.name "GitHub Action"
  git add plots/histogram_*.png || echo "No plot generated"
  git diff --cached --exit-code || git commit -m "Add updated histogram plot" --allow-empty
  # Pull the latest changes and rebase before pushing
  git fetch origin main
  git rebase origin/main
  git push --force-with-lease origin HEAD:main
