name: Process ROOT Data with Plot Commit

on:
  workflow_dispatch:
    inputs:
      data_file:
        description: 'Path to the CSV input file'
        default: 'data.csv'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.read_file.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read CSV File and Prepare Jobs
        id: read_file
        run: |
          files=$(jq -R -s -c 'split("\n")[:-1]' < ${{ github.event.inputs.data_file }})
          echo "files=$files" >> $GITHUB_OUTPUT      

  process-file:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(needs.setup.outputs.files) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ROOT Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            cmake \
            git \
            build-essential \
            libssl-dev \
            libxpm-dev \
            libxft-dev \
            libxext-dev \
            gfortran \
            libpcre3-dev \
            libglu1-mesa-dev \
            libglew-dev \
            libftgl-dev \
            libmysqlclient-dev \
            libfftw3-dev \
            libcfitsio-dev \
            graphviz-dev \
            libavahi-compat-libdnssd-dev \
            libldap2-dev \
            python3-dev \
            libxml2-dev \
            libkrb5-dev \
            libgsl-dev \
            libqt5opengl5-dev \
            qtwebengine5-dev \
            libbz2-dev \
            liblzma-dev \
            libdavix-dev \
            libtbb-dev

      - name: Clone and Build ROOT from Source
        run: |
          # Clone the ROOT repository
          git clone --branch v6-32-06 --depth 1 https://github.com/root-project/root.git
          mkdir root/build
          cd root/build
          
          # Configure the build
          cmake .. -DCMAKE_INSTALL_PREFIX=../install
          
          # Build and install ROOT
          make -j$(nproc)
          make install

      - name: Set ROOT Environment
        run: |
          source root/install/bin/thisroot.sh

      - name: Run ROOT Data Processing Script
        env:
          ROOT_FILE: ${{ matrix.file }}
        run: |
          source root/install/bin/thisroot.sh
          python example.py "$ROOT_FILE"

      - name: Commit and Push Histogram Plot
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add plots/histogram_*.png || echo "No plot generated"
          git diff --cached --exit-code || git commit -m "Add updated histogram plot" --allow-empty
          git push --force-with-lease origin HEAD:main
