name: Process ROOT Data with Plot Commit

on:
  workflow_dispatch:
    inputs:
      data_file:
        description: 'Path to the CSV input file'
        default: 'data.csv'
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      files: ${{ steps.read_file.outputs.files }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read CSV File and Prepare Jobs
        id: read_file
        run: |
          files=$(jq -R -s -c 'split("\n")[:-1]' < ${{ github.event.inputs.data_file }})
          echo "files=$files" >> $GITHUB_OUTPUT      

  process-file:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        file: ${{ fromJSON(needs.setup.outputs.files) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install ROOT
        run: |
          ROOT_VERSION=6.32.06
          OS_VERSION=ubuntu22
          ARCH=x86_64
          wget https://root.cern/download/root_v6.32.06.source.tar.gz
          tar -xzvf root_v6.32.06.source.tar.gz
          source root/bin/thisroot.sh

      - name: Run ROOT Data Processing Script
        env:
          ROOT_FILE: ${{ matrix.file }}
        run: |
          python example.py "$ROOT_FILE"

      - name: Commit and Push Histogram Plot
        if: always()
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add plots/histogram_*.png
          git diff --cached --exit-code || git commit -m "Add updated histogram plot" --allow-empty
          git push --force-with-lease origin HEAD:main

